sudo: required
dist: trusty


language: java
jdk:
  - oraclejdk8


cache:
  directories:
    - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials


install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V


script:
  - ./travis/publish.sh

branches:
  except:
    - /^[0-9]/

#after_success:
#  - mvn jacoco:report coveralls:report
after_success:
  - mvn clean test jacoco:report coveralls:report



env:
  global:
    # Ex. travis encrypt BINTRAY_USER=your_github_account
    - secure: "YLd8r4VTA+HCdUXMeExqog6Av2SCCuEJVYKkg6OxZKjEBN7ZtpNM5tr9nyRHOPZVUMzzAF5NOwxeSXlfvveIikEUfJeMdenFL/4zRAZdc5/N6AAb9IGE3x7dvSj9JS2Q3v6wrMCCf77itZzCqOxFlDVw105npN/ybHlHGm7Uqlhr+z7j1kszU17b98zXn7oAprwqQMeZzgbjPM9mXrqvSrvZhIFNQERUewBx28cMdVVPWDRNmTdMCLcXg4Ugdov+COV7BX1/gwSAdQyNNhMaa6vJ4K3hbxQFBlSDB51d9dV64i6Lke+AykaejaRiOshpHnNuP6dp56jwG/fT0/6nmPKfgbJaTDfsEefsubXANGOd7D98RGVEFSwwCzpR1dmrihHZDi852FIEfHcZwkEIVEcLcvY/OY9UhucjrH/Eh8LyrXdthIv5Esu0t4mBySftlFWA1GkODDvxHylPoqPahdX7rZUE2dx29iuuXO4qRTl9LFEYBALh+Er2oWJIfzsDdN/+3qSgl+99vFW+J2W1BBZOeHbRZP9n/1nM46NTb/XoBu62/cF+I/i2N87ctJzx9S2mfRCbXcOrEJYltzlAfK9+OrhI3CsVCrnAF1mUTJPvSIDJF0ufmlT1KavHzVwiGtexkcKw+tjdRxaYs+CYqHncI31dnE4WK4L9mMeOSC4"

    # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx
    - secure: "N09J5nqjvTc5aPNH/NLdeHGsJR+MGWI+dozTNsPfKEehMmn1CESC+xKrgM1xWvSyS/qka3jRfuytGRkRhpvzgKrMZMCQQdvTWE+H5qtTliYv/gSHzqVH0XmurYa76bVZI46MRI6AeRgXfWvPkexceTP+3U71conADuMcFzE01fWlwyWKQu1nBkphMWRnpIWxwV0nHHiEa6DfzkIlJbfXo6WgS9ZSUvoGsNNC1JwOgDabzVlVxX1ICkMvqWcFIg7PAXv5hpzCAdfcL+zeUhWVokIaiHlgJ43vpbrLMk010IeMe9LYh6k7CC5RnLhNgkvnVWyAnHxZFMpbzGiaIDjiNfSnE2cCwqxkYwkWu2miijx5mkIY6n19m+w8uIvBNhdi6GEwgHF30p8CglTfvZoW3fo4xJOobkqauVi2z3F0NelO/FVLZm0yypbJ4IYgFOtPW2uyNPaYwkpUnSXhXOQUFgu4ac70F1M5B/d/z3hDxl++xT0Ij+wgSvuBf6Fwn4n7HrI/qgK7gc8F3THqVvt0gd3VWP/qilnTn3EllBqZ/SNk32SVPoIMleQISkEoLSpgSxnPrtBuDZnALXali5rYAuQ7kxBp82HDPriOjMNLEJl7qSradoHTj7u7MOWgC/ax7f3L284SWbWfFNBxzheufXdBFCqGJHVfkBcKNDVijSk"

    # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX
    - secure: "mLh+SU416qeNCVw5ckgmlP8K02Ly24AxCxuaIEKPLuy3FmPccovKM4JDk5WP9fB9gVPEFaRpqnvUD9/8Z56DaE7H3tjbwY4vCf3uXS5iT0QPuyj2p0upp+UKTtNO98Q7lZ0p+EC/tZ3FSECHxP/sZxJ6iyM4JCd0FWwLlryzpcSC3vD71kvd7KMzwhC2/nTpi6Olh/DH7fohDVURvyJAOuyoFqilxQI3CuuI1tMp9s8JdWk1//TwEmNisdtg/1DKIZlR3JEKVSrMdUcFJMlHi/jbhDbzSrbfGLIHf1R4C383RoTCzCqDtKm3Y+VDZV+HvzZddbeZf2M5TsYp4gbD6y9jGtiTGqK3Pb1Kk647txoWaCZ0rZYhQOs97eRiXvQdqZ/GwF/63EuW67x7A5jFBJRYQ9B6ReGEUdThRA5TAP7HysvchddNLZE1AI1YDGbdhlj4zAYV+X7owrtliIx9zDtpDKF1ETnUJ6mn2nHPza2nCQHPDPFeJB+JB1HK3P3BdCgbbdg31nGLwt0f7d0gdZX6zL4k+DlSSb0bagQm0+hC6/0+5es7UpUWm0rwMiC/fZRSG1/9qd66OzXZddflToaTeRk3VKINq0nmvKKlwxWt3YNA8MGBJz+Jn72AU0Mc7zZgDcyjpr1TMjZTI3olm2TY0jSyWCcgmEL3l6C+wYc"

    # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
    - secure: "blvwO4dJ+THB9YzFMN+AOAH97npyfmY+1Fp/hb3IIv+eBtke1F3DuY+X681Yfy41BV0rU4TBLyT2bEaS6893gdlujdj1Q5XhPBEqkn0ErNYQDjXesQwfBu5iGqml0aJmuNAVLCAhWa1wIOQY8rn4si9SWQqLOOl2ndhWgJ1Z1w5j6dJAgfUGlP/nnSwN4+GaPtDAufKOqsgpTwXr1QLmPLy+uYHL1Qgz6O/YjAcEAoNnCa/0XQ1Wyk7SX8HjSkeAIYQ8xODBExTXlfttM2Ly+osVWeObVP4B6naQ6kd7Kck1HELTmHL0GMOdt2jxQS/RcPt8SdNVEcKKB0NdO1ZrJuss9xoWIsP8EOVhtbTvYEGLVe39OAkK7Fyd07smDqr92KtvTfOvtJ5725LLaBiX+yHs4BCY3YWHJh7+mBJTpHBLwvFWfT9BlxX/RSgKqtH0GFvc+D0k2/dno2KPpkQPMXWZreMOpDpMbRTR3OGbKoEUOum1uCRWpOx5/cWY6urgJi+QAmaCuKVGVbALRlx3LC5AxKbpCgzux4nqkRGBaVaOhg4nBFqcdoCZWgEYeGBzCpMQj7LP59QZkqIN+mKS5pNBqNa66Yti5TkpHGfKv/hAjYtqSvkEEmsIWr9aXohcsdNaJTtaQmZrhjWHjCNr7HIKF3wBal2/ID3zG/i9qQU="

    # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
    - secure: "FEcWG/GHgdt3OaE949cze7GDF/4EVgoSfI/mCTwnsNWurcSgDNlUCvWA5/K0gxkJVRZPNO+Unc5ndMaKppiPfU+UfByD/jODL2pD0p7gPnuUoCR97QPcmAUOU933AcV+LnOypAeL84al5vDQqyYJX5M1rNQ67HVaCJnm03Z7fuC/ok7bS5L+6bVdAqahhNjD2eeLwAUBeMaqEi3fnayihUVEiNEXHUIt5IPnZmQXXM+SZRTCrfzeJ/+w5BmzI5MnzpoNE3KSuClQehYVhjXkGWlQVhVTRziRfEtEL9pkwcIL2pclNS/20U5XDYU8FRYAN3P4AV09tfx9ts3wI5jIerZPiGOcieTHlTD76A7CkT7+97gXaDYueDC4HdoeorCIMtXtNs0w7Ta/dDHH5GLCyF7hL6VVjGoGzKSMfteP0Z+ZgB7+2IGbl795ApDaxHd0b9mfcQvjYUK/gMt5Qwuo+MLc0SDI0+/S9uTUDZBNkM8iNUHxixkTP4S92BTbH1jJb656OFTRc/DgepTeRHQ6aNbSGSiO58VNkNdbPj3wcWXJGJ3ucIihQ5BDlydZ89XDaimRPUGaygm1YcQ9XG7yb3ge1+CUDcxKJqca0rm4leNdD51Bqg6DGSLvbjlvonmLLA5DiXtNinYW2pRIe1n7NfcBSdmC5aXfHRVPkRORUDg="

