sudo: required
dist: trusty


language: java
jdk:
  - oraclejdk8


cache:
  directories:
    - $HOME/.m2/repository

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"

  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials


install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

deploy:
  # Deploy releases to bintray
  - provider: bintray
    skip_cleanup: true        # required to prevent Travis from cleaning the workspace before deployment
#    file: target/bintray.json # defines the Bintray project to deploy to, and what to deploy and where to.
    user: hotdust # fill in your account name
    key: $BINTRAY_API_KEY            # reference to your Bintray API key
    on: # only deploy when
      repo: hotdust/travis-test # only for this repo
#      tags: true                           # and only when a (release) tag was set


branches:
  except:
    - /^[0-9]/

#after_success:
#  - mvn jacoco:report coveralls:report
after_success:
  - mvn clean test jacoco:report coveralls:report



env:
  global:
    # Ex. travis encrypt BINTRAY_USER=your_github_account
    - secure: "YLd8r4VTA+HCdUXMeExqog6Av2SCCuEJVYKkg6OxZKjEBN7ZtpNM5tr9nyRHOPZVUMzzAF5NOwxeSXlfvveIikEUfJeMdenFL/4zRAZdc5/N6AAb9IGE3x7dvSj9JS2Q3v6wrMCCf77itZzCqOxFlDVw105npN/ybHlHGm7Uqlhr+z7j1kszU17b98zXn7oAprwqQMeZzgbjPM9mXrqvSrvZhIFNQERUewBx28cMdVVPWDRNmTdMCLcXg4Ugdov+COV7BX1/gwSAdQyNNhMaa6vJ4K3hbxQFBlSDB51d9dV64i6Lke+AykaejaRiOshpHnNuP6dp56jwG/fT0/6nmPKfgbJaTDfsEefsubXANGOd7D98RGVEFSwwCzpR1dmrihHZDi852FIEfHcZwkEIVEcLcvY/OY9UhucjrH/Eh8LyrXdthIv5Esu0t4mBySftlFWA1GkODDvxHylPoqPahdX7rZUE2dx29iuuXO4qRTl9LFEYBALh+Er2oWJIfzsDdN/+3qSgl+99vFW+J2W1BBZOeHbRZP9n/1nM46NTb/XoBu62/cF+I/i2N87ctJzx9S2mfRCbXcOrEJYltzlAfK9+OrhI3CsVCrnAF1mUTJPvSIDJF0ufmlT1KavHzVwiGtexkcKw+tjdRxaYs+CYqHncI31dnE4WK4L9mMeOSC4"

    # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
    - secure: "N09J5nqjvTc5aPNH/NLdeHGsJR+MGWI+dozTNsPfKEehMmn1CESC+xKrgM1xWvSyS/qka3jRfuytGRkRhpvzgKrMZMCQQdvTWE+H5qtTliYv/gSHzqVH0XmurYa76bVZI46MRI6AeRgXfWvPkexceTP+3U71conADuMcFzE01fWlwyWKQu1nBkphMWRnpIWxwV0nHHiEa6DfzkIlJbfXo6WgS9ZSUvoGsNNC1JwOgDabzVlVxX1ICkMvqWcFIg7PAXv5hpzCAdfcL+zeUhWVokIaiHlgJ43vpbrLMk010IeMe9LYh6k7CC5RnLhNgkvnVWyAnHxZFMpbzGiaIDjiNfSnE2cCwqxkYwkWu2miijx5mkIY6n19m+w8uIvBNhdi6GEwgHF30p8CglTfvZoW3fo4xJOobkqauVi2z3F0NelO/FVLZm0yypbJ4IYgFOtPW2uyNPaYwkpUnSXhXOQUFgu4ac70F1M5B/d/z3hDxl++xT0Ij+wgSvuBf6Fwn4n7HrI/qgK7gc8F3THqVvt0gd3VWP/qilnTn3EllBqZ/SNk32SVPoIMleQISkEoLSpgSxnPrtBuDZnALXali5rYAuQ7kxBp82HDPriOjMNLEJl7qSradoHTj7u7MOWgC/ax7f3L284SWbWfFNBxzheufXdBFCqGJHVfkBcKNDVijSk"


