sudo: required
dist: trusty

git:
  # otherwise license plugin fails due to grafted commits
  # see https://github.com/travis-ci/travis-ci/issues/7254#issuecomment-387689631
  depth: false

language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2/repository

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
