sudo: required
dist: trusty


language: java
jdk:
  - oraclejdk8


cache:
  directories:
    - $HOME/.m2/repository

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
